### Create a job (invalid printer - should 400)
POST http://localhost:5164/PrintJob
Content-Type: application/json

{
  "submittedBy": "test",
  "fileName": "test.pdf",
  "rawData": "aGVsbG8=",
  "contentType": "application/pdf",
  "printerId": "00000000-0000-0000-0000-000000000000"
}
### Create a job (valid printer)
POST http://localhost:5164/PrintJob
Content-Type: application/json

{
  "submittedBy": "test-retry",
  "fileName": "test.pdf",
  "rawData": "aGVsbG8=",
  "contentType": "application/pdf",
  "printerId": "719368c4-976c-47c2-abff-051d54ebc251"
}
### Get a job (invalid job - should 400)
GET http://localhost:5164/PrintJob/00000000-0000-0000-0000-000000000000

### Get a job (valid job)
GET http://localhost:5164/PrintJob/e0ecda24-2a9f-40a9-a697-a59a549951fb

### Get all active job
GET http://localhost:5164/PrintJob/

### HealthChecks
GET http://localhost:5164/health

### logs
GET http://localhost:5164/Logs
Content-Type: application/json

{
  searchTerms =  null,
  dateFrom = null,
  DateTo = null,
  ActionFilter = null,
  PerformedBy = null,
  Page = 1;
  PageSize  = 50;
}


### Cancel a job (valid job)
DELETE http://localhost:5164/PrintJob/9085a148-7ecf-4b73-8099-b8eaace95324


### Create a printer
POST http://localhost:5164/Printer
Content-Type: application/json

{
  "Ipaddress": "ipp://HPD0AD08C445FE.local:631/ipp/print",
  "Name": "TEST DUP"
}


### Get a printer (valid)
GET http://localhost:5164/Printer/719368c4-976c-47c2-abff-051d54ebc251

### Get a printer (400)
GET http://localhost:5164/Printer/00000000-0000-0000-0000-000000000000



